# Generated by Django 5.2.17 on 2026-09-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "audio_analytics",
            "0009_rename_audio_analy_payment_user_idx_audio_analy_user_id_64d3b2_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="audioanalysis",
            name="transcript",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="audioanalysis",
            name="transcript_segments",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audioanalysis",
            name="transcription_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audioanalysis",
            name="transcription_language",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
